name: chaosmuse.github.io
description: Ramblings of an eclectic woman
url: https://chaosmuse.github.io
baseurl: /

markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
textile_ext: textile

highlighter: rouge
excerpt_separator: ""

paginate: 1
paginate_path: "page:num"
permalink: /:year/:month/:day/:title/

source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts

navigation:
 - name: Posts
   path: /categories
 - name: Projects
   path: /projects/
 - name: Resources
   path: /resources/
 - name: About
   path: /about/

theme: jekyll-theme-minimal
