name: jmagas
markdown: rdiscount
pygments: true
paginate: 1
paginate_path: "page:num"

navigation:
 - name: Posts
   path: blog/
 - name: Projects
   path: projects.html
 - name: Resources
   path: resources.html
 - name: About
   path: about.html
