name: jmagas
markdown: redcarpet
pygments: true
paginate: 1
paginate_path: "page:num"

navigation:
 - name: Home
   path: /
 - name: Projects
   path: /projects/
 - name: Resources
   path: /resources/
 - name: About
   path: /about/
 - name: License
   path: /license/
